SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BUSINESS;
SELECT * FROM TBL_SUPER_CAR;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_REPLY;
SELECT * FROM TBL_PET;
SELECT * FROM TBL_OWNER;
SELECT * FROM TBL_FILE;
SELECT * FROM TBL_QUESTION;
SELECT * FROM TBL_ANSWER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_LIKE;
SELECT * FROM TBL_EMPLOYEE;

SELECT B.ID, B.BOARD_TITLE, B.BOARD_CONTENT, COUNT(B.ID) LIKE_COUNT 
FROM TBL_BOARD B LEFT OUTER JOIN TBL_LIKE L
ON B.ID = L.BOARD_ID
GROUP BY B.ID, B.BOARD_TITLE, B.BOARD_CONTENT;

SELECT ROWNUM R, B.* FROM TBL_BOARD B ORDER BY ROWNUM DESC;

SELECT BOARD.* FROM 
(
	SELECT ROWNUM R, B.* FROM TBL_BOARD B ORDER BY ROWNUM DESC
) BOARD
WHERE
R BETWEEN 
(
	SELECT R - 3 FROM 
	(
		SELECT ROWNUM R, B.* FROM TBL_BOARD B ORDER BY ROWNUM DESC
	)
	WHERE ID = 1522
)
AND 
(
	SELECT R + 3 FROM 
	(
		SELECT ROWNUM R, B.* FROM TBL_BOARD B ORDER BY ROWNUM DESC
	)
	WHERE ID = 1522
);

SELECT ID, PREV FROM (SELECT ID, LAG(ID) OVER(ORDER BY ID DESC) PREV FROM TBL_BOARD) WHERE ID = 1522;
SELECT ID, PREV FROM (SELECT ID, LEAD(ID) OVER(ORDER BY ID DESC) PREV FROM TBL_BOARD) WHERE ID = 1522;










